# Generated by Django 4.1.4 on 2023-08-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumps_up', models.PositiveIntegerField(null=True)),
                ('wow', models.PositiveIntegerField(null=True)),
                ('rocket', models.PositiveIntegerField(null=True)),
                ('coffee', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postinstance',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.reactions'),
        ),
    ]
