# Generated by Django 4.1.4 on 2023-08-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reactions_postinstance_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinstance',
            name='reactions',
        ),
        migrations.AddField(
            model_name='reactions',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postinstance'),
        ),
    ]
